"""
Cognitive Laws — Three System Laws
==================================
The three ironclad cognitive laws that govern all orchestration decisions.
Source: teonu-worldmodel architecture.
"""

from enum import Enum


class CognitiveLaws:
    """
    Three-system cognitive laws.
    All L3 meta-cognitive scheduling must comply with these three laws.
    """

    # ── Law I: Assumption ≠ Fact ──────────────────────────────────────────────
    # Inferences generated by LWG must be marked with confidence <= 0.6.
    # Inferences cannot be used directly as facts; they must be validated.
    LWG_INFERENCE_MAX_CONFIDENCE = 0.6

    # ── Law II: Cognition Must Be Compressible ───────────────────────────────
    # When history exceeds MAX_HISTORY entries → auto-summarise.
    # When pending tasks time out → auto-forget or escalate to alert.
    MAX_HISTORY = 10
    PENDING_TIMEOUT_SECONDS = 300

    # ── Law III: Context Must Be Budget-Constrained ─────────────────────────
    # When token budget is exhausted, preserve stable + high-confidence nodes first.
    DEFAULT_TOKEN_BUDGET = 2000
